---
# tasks file for rtindru.flower-celery

- name: Install Flower
  pip:
    name: flower
    version: "{{ flower_version }}"
    state: present
  when: not flower_bin

- name: Install Upstart script
  template:
    src: upstart.conf.j2
    dest: "/etc/init/{{ flower_app_name }}-flower.conf"
  when: flower_service == 'upstart'
  notify: flower reload

- name: Install SystemD script
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ flower_app_name }}-flower.service"
  when: flower_service == 'systemd'
  notify: flower restart

- name: Setup Nginx configuration
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ flower_app_name }}-flower.conf"
    owner: "{{ flower_user }}"
    group: "{{ flower_group }}"
  when: flower_nginx
  notify: nginx reload

- name: Enable nginx site
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ flower_app_name }}-flower.conf"
    dest: "/etc/nginx/sites-enabled/{{ flower_app_name }}-flower.conf"
  when: flower_nginx
  notify: nginx restart
