---
# handlers file for rtindru.flower-celery

- name: flower restart
  service:
    name: "{{ flower_app_name }}-flower"
    state: restarted

- name: flower reload
  service:
    name: "{{ flower_app_name }}-flower"
    state: reloaded

- name: nginx reload
  service:
    name: nginx
    state: reloaded
