---
# handlers file for rtindru.flower-celery

- name: Restart Flower
  service: name={{ flower_app_name }}-flower state=restarted
  become: true
  become_method: sudo

- name: Reload Flower
  service: name={{ flower_app_name }}-flower state=reloaded
  become: true
  become_method: sudo
